---
title: "ESG News"
author: "Angus Macdonald"
date: "2023-11-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r config, include=FALSE}
dir_root <- getwd()

# Load packages
load_packages <- paste(dir_root,"/FinalScripts/load_packages_webscrape.R", sep = "")
source(load_packages)
```

## R Markdown

Welcome to ESG News. This report summarizes the latest news according to several main ESG news sites. 


## Latest News

Here are the latest news articles from ESG News.

```{r pressure, echo=FALSE}
library(rvest)
library(knitr)

# URL of the "ESG News" website
url <- "https://esgnews.com"

# Read the HTML content from the webpage
webpage <- read_html(url)

# Extract all article titles using CSS selectors
titles <- webpage %>%
  html_nodes(".tt-breaking-post a") %>%
  html_text()

# Extract all article links  using CSS selectors
links <- webpage %>%
  html_nodes(".tt-breaking-post a") %>%
  html_attr("href")

# Fetching the first 10 articles
first_10_titles <- titles[1:5]
first_10_links <- links[1:5]

# Combine titles and links into a data frame
data <- data.frame(Title = first_10_titles, Link = first_10_links)

kable(data, caption = "Latest News from ESG News")
```

## Latest Share Prices

The latest share price for Apple can be seen below:

```{r testfunction, echo=FALSE}
my_data <- fetch_shareprice("AAPL")
kable(my_data, caption = "Latest Share Price of Apple")
```